version: '3.8'
services:
  db:
    container_name: compose-db-container
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=journal
      - POSTGRES_HOST=db # https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
    volumes:
      # - ./db:/var/lib/postgresql/data # --> uncomment to create db folder in root dir and persist data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    container_name: compose-web-container
    restart: always
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
    - .:/usr/src/app