version: '3.8'
services:
  db:
    container_name: compose-db-container
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST} # https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
    volumes:
      #- ./db:/var/lib/postgresql/data # --> uncomment to create db folder in root dir and persist data after stopping containers
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    container_name: compose-web-container
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app